### ISSUE TITLE
Android_mic_streaming - can't get any results from speech

### ISSUE THREAD

**Issue by jose-alvessh** [mozilla/STT-examples#24]
Hello, 

I'm trying this Android Sample App but every time I speak I can't get any result. 
I have downloaded to my computer and I have copied the models from the release 0.6.1 to my tablet. I am using a Samsung Galaxy tab 10.1 - 2016. 

The model is created since I can get on the TextView the answer "Created model" and the Log "I/tflite: Initialised TensorFlow Lite runtime.". Thus, I think the model is created correctly.  However, I have noticed that every time I press stop listening I get this following Log:
"I/Choreographer: Skipped X frames!  The application may be doing too much work on its main thread." Is this the reason why I'm not getting any result?
I have tried to use the model from this release using python (translating a .wav from collected using the same device) and it has worked well.

Anyone else that have had this error? 
Could you help me solving it?
Thanks in advance

**Comment by lissyx** [comment]
> However, I have noticed that every time I press stop listening I get this following Log:
> "I/Choreographer: Skipped X frames! The application may be doing too much work on its main thread." Is this the reason why I'm not getting any result?

It could very likely be 

>  Samsung Galaxy tab 10.1 - 2016.

I fear your SoC is just too slow.

**Comment by lissyx** [comment]
Maybe @erksch can shed some light?

**Comment by erksch** [comment]
Sorry I was a little bit occupied this week.
Like @lissyx suggested, maybe your device is not capable of running the models. Have you tried another device? According to [this stackoverflow](https://stackoverflow.com/questions/14678593/the-application-may-be-doing-too-much-work-on-its-main-thread) the error it is due to heavy processing and maybe just requires a stronger phone.

**Comment by jose-alvessh** [comment]
Hi @erksch! I have tried today with exactly the same models and the same App on a Samsung S8 and I still get the same results. 
Do you have sure that this problem is related with the power of each device?

**Comment by lissyx** [comment]
> Hi @erksch! I have tried today with exactly the same models and the same App on a Samsung S8 and I still get the same results.
> Do you have sure that this problem is related with the power of each device?

@jose-alvessh Could you give your exact S8 model ? There are some with Snapdragon 835 which should yield good results, but there are some with Exynos SoC and we have no idea of the performances on those.

**Comment by lissyx** [comment]
> > Hi @erksch! I have tried today with exactly the same models and the same App on a Samsung S8 and I still get the same results.
> > Do you have sure that this problem is related with the power of each device?
> 
> @jose-alvessh Could you give your exact S8 model ? There are some with Snapdragon 835 which should yield good results, but there are some with Exynos SoC and we have no idea of the performances on those.

Specifically, according to https://www.gsmarena.com/samsung_galaxy_s8-8161.php the Exynos 8895 has little.BIG arch with some 1.7GHz Cortex-A53 that might be quite slow.

**Comment by jose-alvessh** [comment]
@lissyx thanks for the reply. Howevet @erksch has told me that he ran it correctly with the Huawei P20. By this page https://www.gsmarena.com/compare.php3?idPhone1=9107&idPhone2=8161 it seems that the CPUs are really similar (both have 4x the Cortex-A53 but the Huawei has slightly higher clock speed). 
How can we explain that the difference is that significative between both smartphones? 
Thanks in advance

**Comment by lissyx** [comment]
>  How can we explain that the difference is that significative between both smartphones?

Hard to tell without checking more on the hw itself.
I note that you have not documented any perfs infos on your latest tries, whether you get the exact same error, etc.

You have not also shared us whether you have the Snapdragon or the Exynos version.

Note also that the Huawei is Kirin 970 which has some NN android acceleration as much as I can tell.

**Comment by erksch** [comment]
@jose-alvessh Actually, how many frames are skipped? You just typed X in the original question. Does the amount of frames skipped differ for different devices? The [stackoverflow post](https://stackoverflow.com/questions/14678593/the-application-may-be-doing-too-much-work-on-its-main-thread) I talked about suggests extracting heavy logic to a separate thread to fix the problem, the implementation is already doing that. Have you tried debugging to which you come?

Since "Created model" was displayed, It should fail somewhere here:
```kotlin
// ... "Created model" is printed
btnStartInference.text = "Stop Recording"
streamContext = model.createStream()

if (recorder == null) {
  recorder = AudioRecord(
    MediaRecorder.AudioSource.VOICE_RECOGNITION,
    model.sampleRate(),
    RECORDER_CHANNELS,
    RECORDER_AUDIO_ENCODING,
    NUM_BUFFER_ELEMENTS * BYTES_PER_ELEMENT)
}

recorder?.startRecording()
isRecording = true

if (recordingThread == null) {
  // I assume here as soon as the transcription thread starts?
  recordingThread = Thread(Runnable { transcribe() }, "AudioRecorder Thread")
  recordingThread?.start()
}
```

**Comment by saulpark** [comment]
Hi @lissyx and @erksch , I'm having a similar issue, I'm running the application with this Spanish model  https://drive.google.com/drive/folders/1-3UgQBtzEf8QcH2qc8TJHkUqCBp5BBmO. In one of the devices (Android 10) works very well, but in the 3 remaining ones the result is very bad taking between 3 to 5 seconds in recognizing one word (alerta) and sometimes jus never return any transcription but just some random letters.

I understand that 2 of the devices are older, but the device with Android 6 (P9 Lite) shows the same symptoms and have very capable hardware. 

Additionally when I test it in the emulator inside Android studio with all versions of Android works very well.

I already try to separate the data reading from the mic in a different Thread of the transcription Thread, but I'm getting the same result.

Is it possible that the version of Android can cause this behavior?

- Dual-core 1.2 GHz Cortex-A7 | 512MB RAM | Galaxy J1 | Android 6
- Octa-core (4x2.0 GHz Cortex-A53 & 4x1.7 GHz Cortex-A53) | 3GB RAM | P9 Lite | Android 6
- Quad-core 1.4 GHz Cortex-A53 | 4GB RAM | Galaxy J6 | Android 9
- Octa-core (2x2.0 GHz 360 Gold & 6x1.7 GHz Kryo 360 Silver) | 4GB RAM | Pixel 3a | Android 10

Thank in advise.

**Comment by lissyx** [comment]
> Is it possible that the version of Android can cause this behavior?

We dont have support for Android < 7, so I dont get how you can run it on Android 6. That being said, 4x Cortex A53 is very close to the limit for realtime support, and depending on hardware it might not be enough. The v0.8 should help with that.

**Comment by lissyx** [comment]
Moving to DeepSpeech r0.8 release should help now that TFLite can use threads and the current example is known to work on a lot of other devices.
