### ISSUE TITLE
donet example not working with DeepSpeech NuGet

### ISSUE THREAD

**Issue by profwillie** [mozilla/STT-examples#34]
I am trying to run the .Net example DeepSpeech.WPF.  Right now, it depends on the DeepSpeechClient project, but I removed that because I need to get this working from the NuGet.  (I am not requiring everyone to build the client when there should be a working NuGet)

Replacing the project with the NuGet gets the code to compile, but then I get a runtime error:
 
Cannot find the model file: output_graph.pbmm

How do I get this model file (and any others I may need) without building the client myself?  Should the model files be included with the NuGet?  Are there instructions for getting all the additional files one may need to get the NuGet to work?

**Comment by carlfm01** [comment]
For English all the required files are in the release page: https://github.com/mozilla/DeepSpeech/releases



>  Should the model files be included with the NuGet

No, too big.

**Comment by willieNU** [comment]
Thank you.  I have it running now.

Could the example be updated to use the NuGet?  And could the documentation make it clear that you need to separately download the model file.  I agree it is too large to be included in the NuGet.

**Comment by carlfm01** [comment]
> Could the example be updated to use the NuGet?

Send a PR? I can review :) 



> And could the documentation make it clear that you need to separately download the model file

Maybe related to :https://github.com/mozilla/DeepSpeech/issues/2948 

A PR to help Reuben? The ideal would be add a readme inside the NuGet and once it gets installed the readme pops, have you seen that type of readme? 

>  I agree it is too large to be included in the NuGet.

And there can be multiple models with multiple languages for a single client.

**Comment by willieNU** [comment]
PR for example to use NuGet has been sent.

I'm not familiar enough with NuGet to know how to provide instructions that pop up, or even if that is possible.  I think just a little documentation that says to download the model file from the release may be sufficient.

**Comment by lissyx** [comment]
I believe this is now fixed
