### ISSUE TITLE
Add Python version and test.sh instructions

### ISSUE THREAD

**Issue by huertanix** [mozilla/STT-examples#67]
Currently, the README file for `Microphone VAD Streaming` does not mention what version of Python is needed to run it. Would be good to include it.

A file named `test.sh` also exists in that repo but includes no instructions on its use. Would be great to have those included.

**Comment by lissyx** [comment]
> A file named `test.sh` also exists in that repo but includes no instructions on its use. Would be great to have those included.

No, this is to run our CI
