### ISSUE TITLE
Android: Access denied on data directory

### ISSUE THREAD

**Issue by zaptrem** [mozilla/STT-examples#77]
Running `adb push deepspeech-0.8.0-models.tflite deepspeech-0.8.0-models.scorer /storage/emulated/0/Android/data/org.deepspeechdemo/files/`

Gives a permission denied error with the latest sdk Android Studio Pixel emulator. How did you work around this?

**Comment by lissyx** [comment]
Maybe you need to create it ? Run the app ? Or mkdir ?

**Comment by zaptrem** [comment]
I changed the location the models are stored in to data/data/com.appname.example and worked around this issue. However, now the app crashes whenever I click the "stop recording" button the demo crashes with this error in Logcat:

2020-08-17 22:29:17.514 24046-24046/org.deepspeechdemo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7da47030 in tid 24046 (.deepspeechdemo), pid 24046 (.deepspeechdemo)

Any idea what could be causing that?

**Comment by lissyx** [comment]
> Any idea what could be causing that?
> Edit: #78

No, and as documented, those examples are here to demo the use of the API but we can't provide any kind of guarantee regarding the fact that they work. I know nothing about Kotlin, and I really can't see this issue now.
